### 异常处理机制(try-catch)

语法:
```
try{
  代码片段
  String str = null;
  System.out.println(str.length());
  //在try语句块中出错代码以下的内容都不会执行  
}catch(xxxException e){
  当try中出现xxxException后的处理代码
}catch(xxxException e){
  catch是可以定义多个的，针对try中不同异常我们可以分别去捕获并处理
}catch(Exception e){
  我们可以在最后catch处捕获Exception以避免因为一个未捕获的异常导致程序中断
}finally{
   怎样都必执行
}
```
>当JVM执行代码时遇到了某个异常时，会实例化对应的异常实例并将其抛出。

>finally块（不管try中有没有return都执行）

finally语句块是在异常处理机制的最后一块，可以直接跟在try之后或者最后一个catch之后。
finally块可以保证只要程序执行到try当中，无论try当中的代码是否出现了异常funally都必定执行。
finally中通常不能写return,否则必定返回finally中return的内容

**通常我们可以将释放资源这样的操作放在这里，比如IO操作完毕后的关闭流**

## 在异常处理机制中操作IO

例:
```
FileOutputStream fos = null;
try {
    fos = new FileOutputStream("pw.txt");
    fos.write(1);
    return;
}catch(FileNotFoundException e) {
    e.printStackTrace();
} 
catch (IOException e) {
    e.printStackTrace();
}finally {
    try {
        if(fos!=null) {
            fos.close();
        }
    } catch (IOException e) {
        e.printStackTrace();
    }
}
```

>JDK7之后推出了一个特性:自动关闭Autocloseable

例:
```
try(
	//只有实现了AutoCloseable接口的类可以在这里定义并初始化。像流和RandomAccessFile都实现了该接口。
    //被定义在这里的内容会被编译器最终改为在finally中关闭。
	FileOutputStream fos = new FileOutputStream("pw.txt");
){
	fos.write(1);
}catch(FileNotFoundException e) {
	e.printStackTrace();
} 
catch (IOException e) {
	e.printStackTrace();
}
```

## throw 

>通常使用throw主动对外抛出异常会在以下情况发生

1:程序确实出现了异常，但是该异常不应当在当前代码片段被解决时可以对外抛出给调用者解决
2:程序遇到一个满足语法要求但是**不满足业务逻辑**要求的情况时可以对外抛出异常

例:
```
if(age<0||age>100) {
    throw new RuntimeException("年龄不合法");
}
```

## throws

>当调用一个含有throws声明异常抛出的方法时，编译器会检查是否有处理该异常，如果没有则编译不通过。

>处理异常的方式有两种:

1.使用try-catch处理该异常
2.在当前方法上继续使用throws声明该异常的抛出
具体用哪种取决于处理异常的责任问题

例:
```
public void setAge(int age) throws Exception{
    if(age<0||age>100) {
    
//使用throw关键字加异常实例，用于对外抛出异常
//当一个方法使用throw抛出一个异常时，只有RuntimeException及其子类型异常被抛出时可以不写throws，
剩下的必须写，否则编译不通过。
        
        throw new Exception("年龄不合法");
    }
    this.age = age;
}
```
>当子类重写父类一个含有throws声明异常抛出的方法时，对throws的重写规则

	1.可以重写跟父类一样的方法
	2.只抛出一部分异常
	3.可以不抛出任何异常
	4.允许抛出超类方法抛出异常的子类型异常
	5.**不允许抛出额外异常**
	6.**不允许抛出超类方法抛出异常的超类异常**

## RuntimeException(非检测异常)

>java异常可以分为可检测异常，非检测异常

1.可检测异常:可检测异常经编译器验证，不捕捉这个异常，编译器就通不过，不允许编译
2.非检测异常: 不遵循处理或声明规则。在产生此类异常时，不一定非要采取任何适当操作，编译器不会检查是否已经解决了这样一个异常。常见有：
>IllegalArgument(抛出的异常表明向方向传递了一个不合法或不正确的参数)

>NullPointerException(当应用程序试图在需要对象的地方使用null时，抛出该异常)

>ArrayIndexOutOfBoundsException(当使用的数组下标超出数组允许范围时，抛出该异常)

>ClassCastException(当试图将对象强制转换为不是实例的子类时，抛出该异常)

>NumberFormatException(当应用程序试图将字符串转换成一种数值类型，但该字符串不能转换为适当格式时，抛出该异常)

## 异常常用方法

```
try {
    String str = "a";
    System.out.println(Integer.parseInt(str));

} catch (Exception e) {
    //1.输出错误堆栈信息，编译debug
    e.printStackTrace();
    
    //2.获取错误信息
    String message = e.getMessage();
}
```

## 自定义异常

>通常用来定义程序中的业务逻辑错误。

**自定义异常创建需要做以下几件事**
1.类名要做到见名知意
2.需要继承自Exception(直接或间接继承均可)
3.定义Exception中定义的各种构造方法
4.提供序列化版本号(因为Exception实现了序列化接口)

例:
```
public class IllegalAgeDemo extends Exception {
	//提供序列化版本号
	private static final long serialVersionUID = 1L;
    
    //自动生成定义构造方法
    ...
}

//抛出自定义异常
public void setAge(int age) throws IllegalAgeDemo{
    if(age<0||age>100) {
        throw new IllegalAgeDemo("年龄不合法");
    }
    this.age = age;
}
```

## finalize

>finalize是Object定义的方法，意味着java中所有的类都有该方法，该方法是GC调用的方法。当一个对象即将被GC释放时，GC会调用该方法，调用完毕后该对象会被释放资源。

**注意:若重写该方法，该方法不能有耗时的操作**









